<?php

$districts = '<select class="browser-default custom-select" id="rdistrict">
	<option value="" selected>Choose answer</option>
	<option value="Aba (South East)">Aba (South East)</option>
	<option value="Abakaliki (South East)">Abakaliki (South East)</option>
	<option value="Abeokuta (Abeokuta)">Abeokuta (Abeokuta)</option>
	<option value="Abesan (Agege)">Abesan (Agege)</option>
	<option value="Abocho (North Central)">Abocho (North Central)</option>
	<option value="Abuja (Abuja)">Abuja (Abuja)</option>
	<option value="Addo (North Central)">Addo (North Central)</option>
	<option value="Ado Ekiti (Akure)">Ado Ekiti (Akure)</option>
	<option value="Afikpo (South East)">Afikpo (South East)</option>
	<option value="Afobaje District">Afobaje District</option>
	<option value="Agbado (Agege)">Agbado (Agege)</option>
	<option value="Agege (Agege)">Agege (Agege)</option>
	<option value="Ahoada (South South)">Ahoada (South South)</option>
	<option value="Ajah Dist (Lekki)">Ajah Dist (Lekki)</option>
	<option value="Ajebo (Abeokuta)">Ajebo (Abeokuta)</option>
	<option value="Ajegunle/Apapa (Yaba)">Ajegunle/Apapa (Yaba)</option>
	<option value="Akowonjo (Agege)">Akowonjo (Agege)</option>
	<option value="Akure (Akure)">Akure (Akure)</option>
	<option value="Akute (Ikeja)">Akute (Ikeja)</option>
	<option value="Akwanga (North Central)">Akwanga (North Central)</option>
	<option value="Alaka (Yaba)">Alaka (Yaba)</option>
	<option value="Alake Dist (Agege)">Alake Dist (Agege)</option>
	<option value="Alapere (Somolu)">Alapere (Somolu)</option>
	<option value="Anthony District">Anthony District</option>
	<option value="Anthony District (Anthony District)">Anthony District (Anthony District)</option>
	<option value="Anyigba (North Central)">Anyigba (North Central)</option>
	<option value="Apeka (Ikorodu)">Apeka (Ikorodu)</option>
	<option value="Asaba (Mid-West)">Asaba (Mid-West)</option>
	<option value="Asokoro District">Asokoro District</option>
	<option value="Asokoro District (Asokoro District)">Asokoro District (Asokoro District)</option>
	<option value="Association Avenue District">Association Avenue District</option>
	<option value="Auchi (Mid-West)">Auchi (Mid-West)</option>
	<option value="Awka (South East)">Awka (South East)</option>
	<option value="Awka Etiti (South East)">Awka Etiti (South East)</option>
	<option value="Ayepe (Akure)">Ayepe (Akure)</option>
	<option value="Badagry (Badagry)">Badagry (Badagry)</option>
	<option value="Bali (North East)">Bali (North East)</option>
	<option value="Baruwa (Agege)">Baruwa (Agege)</option>
	<option value="Bauchi (North East)">Bauchi (North East)</option>
	<option value="Benin1 (Mid-West)">Benin1 (Mid-West)</option>
	<option value="Bida (North Central)">Bida (North Central)</option>
	<option value="Birnin-Kebbi (North West)">Birnin-Kebbi (North West)</option>
	<option value="Bonny (South South)">Bonny (South South)</option>
	<option value="Calabar (South South)">Calabar (South South)</option>
	<option value="Dafa (Abuja)">Dafa (Abuja)</option>
	<option value="Damaturu (North East)">Damaturu (North East)</option>
	<option value="Dst District (Mid-West)">Dst District (Mid-West)</option>
	<option value="Dutse (North West)">Dutse (North West)</option>
	<option value="Effurun (Mid-West)">Effurun (Mid-West)</option>
	<option value="Egbe (Festac)">Egbe (Festac)</option>
	<option value="Eket (South South)">Eket (South South)</option>
	<option value="Ekpan (Mid-West)">Ekpan (Mid-West)</option>
	<option value="Ekpoma (Mid-West)">Ekpoma (Mid-West)</option>
	<option value="Eleshin District">Eleshin District</option>
	<option value="Eleshin District (Eleshin District)">Eleshin District (Eleshin District)</option>
	<option value="Enugu (South East)">Enugu (South East)</option>
	<option value="Epe (Lekki)">Epe (Lekki)</option>
	<option value="Festac (Festac)">Festac (Festac)</option>
	<option value="Galadima Kogo (North Central)">Galadima Kogo (North Central)</option>
	<option value="Gbagada (Somolu)">Gbagada (Somolu)</option>
	<option value="Gombe (North East)">Gombe (North East)</option>
	<option value="Gusau (North West)">Gusau (North West)</option>
	<option value="Iba (Badagry)">Iba (Badagry)</option>
	<option value="Ibadan (Oyo)">Ibadan (Oyo)</option>
	<option value="Ibafo (Ikeja)">Ibafo (Ikeja)</option>
	<option value="Idah (North Central)">Idah (North Central)</option>
	<option value="Ifako (Ikeja)">Ifako (Ikeja)</option>
	<option value="Ife (Akure)">Ife (Akure)</option>
	<option value="Ifo (Sango Ota)">Ifo (Sango Ota)</option>
	<option value="Igbogbo (Ikorodu)">Igbogbo (Ikorodu)</option>
	<option value="Ijebu Igbo/ Waterside District ">Ijebu Igbo/ Waterside District </option>
	<option value="Ijebu Ode (Abeokuta)">Ijebu Ode (Abeokuta)</option>
	<option value="Ijede District">Ijede District</option>
	<option value="Ijede District (Ijede District)">Ijede District (Ijede District)</option>
	<option value="Iju Ishaga (Ikeja)">Iju Ishaga (Ikeja)</option>
	<option value="Ikeja (Ikeja)">Ikeja (Ikeja)</option>
	<option value="Ikere Ekiti (Akure)">Ikere Ekiti (Akure)</option>
	<option value="Ikom (South South)">Ikom (South South)</option>
	<option value="Ikorodu1 (Ikorodu)">Ikorodu1 (Ikorodu)</option>
	<option value="Ikorodu2 (Ikorodu)">Ikorodu2 (Ikorodu)</option>
	<option value="Ikot-Ekpene (South South)">Ikot-Ekpene (South South)</option>
	<option value="Ilaro (Sango Ota)">Ilaro (Sango Ota)</option>
	<option value="Ilesha (Akure)">Ilesha (Akure)</option>
	<option value="Ilorin (Kwara)">Ilorin (Kwara)</option>
	<option value="Ipakodo (Ikorodu)">Ipakodo (Ikorodu)</option>
	<option value="Itaoshin (Abeokuta)">Itaoshin (Abeokuta)</option>
	<option value="Iyana (Oyo)">Iyana (Oyo)</option>
	<option value="Jakande Estate (Festac)">Jakande Estate (Festac)</option>
	<option value="Jalingo (North East)">Jalingo (North East)</option>
	<option value="Jos (North Central)">Jos (North Central)</option>
	<option value="Kaduna (North West)">Kaduna (North West)</option>
	<option value="Kafanchan (North West)">Kafanchan (North West)</option>
	<option value="Kaltungo (North West)">Kaltungo (North West)</option>
	<option value="Kano (North West)">Kano (North West)</option>
	<option value="katsina (North West)">katsina (North West)</option>
	<option value="Katsina- Ala (North Central)">Katsina- Ala (North Central)</option>
	<option value="ketu (Somolu)">ketu (Somolu)</option>
	<option value="Kontagora (North Central)">Kontagora (North Central)</option>
	<option value="Kosubosu (Kwara)">Kosubosu (Kwara)</option>
	<option value="Kubwa (Abuja)">Kubwa (Abuja)</option>
	<option value="Lafia (North Central)">Lafia (North Central)</option>
	<option value="Lagos Island (Lekki)">Lagos Island (Lekki)</option>
	<option value="Lekki (Lekki)">Lekki (Lekki)</option>
	<option value="Life Seminary (Ikorodu)">Life Seminary (Ikorodu)</option>
	<option value="Lokoja (North Central)">Lokoja (North Central)</option>
	<option value="Magodo (Ikeja)">Magodo (Ikeja)</option>
	<option value="Maiduguri (North East)">Maiduguri (North East)</option>
	<option value="Makurdi (North Central)">Makurdi (North Central)</option>
	<option value="Minna (North Central)">Minna (North Central)</option>
	<option value="Molete (Oyo)">Molete (Oyo)</option>
	<option value="Morogbo (Badagry)">Morogbo (Badagry)</option>
	<option value="Mubi (North East)">Mubi (North East)</option>
	<option value="Mushin (Somolu)">Mushin (Somolu)</option>
	<option value="Nathq (Yaba)">Nathq (Yaba)</option>
	<option value="Nsukka (South East)">Nsukka (South East)</option>
	<option value="Numan (North East)">Numan (North East)</option>
	<option value="Nyanya (Abuja)">Nyanya (Abuja)</option>
	<option value="Obada idiemi (Abeokuta)">Obada idiemi (Abeokuta)</option>
	<option value="Ogbe Benin2 (Mid-West)">Ogbe Benin2 (Mid-West)</option>
	<option value="Ogbia (South South)">Ogbia (South South)</option>
	<option value="Ogbomoso (Kwara)">Ogbomoso (Kwara)</option>
	<option value="Ogijo (Ikorodu)">Ogijo (Ikorodu)</option>
	<option value="Ogoja (South South)">Ogoja (South South)</option>
	<option value="Ohafia (South East)">Ohafia (South East)</option>
	<option value="Okenne (North Central)">Okenne (North Central)</option>
	<option value="Okigwe (South East)">Okigwe (South East)</option>
	<option value="Okitipupa (Akure)">Okitipupa (Akure)</option>
	<option value="Okota District">Okota District</option>
	<option value="Omoluabi (Oyo)">Omoluabi (Oyo)</option>
	<option value="Ondo (Akure)">Ondo (Akure)</option>
	<option value="Onitsha (South East)">Onitsha (South East)</option>
	<option value="Onueke (South East)">Onueke (South East)</option>
	<option value="Oregun (Ikeja)">Oregun (Ikeja)</option>
	<option value="Orimedu District">Orimedu District</option>
	<option value="Orimedu District (Orimedu District)">Orimedu District (Orimedu District)</option>
	<option value="Orlu (South East)">Orlu (South East)</option>
	<option value="Oro (Kwara)">Oro (Kwara)</option>
	<option value="Oshodi (Agege)">Oshodi (Agege)</option>
	<option value="Osogbo (Akure)">Osogbo (Akure)</option>
	<option value="Otukpo (North Central)">Otukpo (North Central)</option>
	<option value="Owerri (South East)">Owerri (South East)</option>
	<option value="Owo (Akure)">Owo (Akure)</option>
	<option value="Owode (Sango Ota)">Owode (Sango Ota)</option>
	<option value="Owutu (Ikorodu)">Owutu (Ikorodu)</option>
	<option value="Oye Ekiti (Akure)">Oye Ekiti (Akure)</option>
	<option value="Oyigbo (South South)">Oyigbo (South South)</option>
	<option value="Oyo (Oyo)">Oyo (Oyo)</option>
	<option value="Pankshin (North Central)">Pankshin (North Central)</option>
	<option value="Port-Harcourt (South South)">Port-Harcourt (South South)</option>
	<option value="Saabo (Ikeja)">Saabo (Ikeja)</option>
	<option value="Sabo Oniba (Badagry)">Sabo Oniba (Badagry)</option>
	<option value="Sagamu (Abeokuta)">Sagamu (Abeokuta)</option>
	<option value="Sagbama (South South)">Sagbama (South South)</option>
	<option value="Sango Ota (Sango Ota)">Sango Ota (Sango Ota)</option>
	<option value="Shalom (Oyo)">Shalom (Oyo)</option>
	<option value="Shendam (North Central)">Shendam (North Central)</option>
	<option value="Sokoto (North West)">Sokoto (North West)</option>
	<option value="Somolu (Somolu)">Somolu (Somolu)</option>
	<option value="Suleja (Abuja)">Suleja (Abuja)</option>
	<option value="Surulere (Yaba)">Surulere (Yaba)</option>
	<option value="Tomori (Sango Ota)">Tomori (Sango Ota)</option>
	<option value="Ubeji (Mid-West)">Ubeji (Mid-West)</option>
	<option value="Udi (South East)">Udi (South East)</option>
	<option value="Ughelli District (Mid-West)">Ughelli District (Mid-West)</option>
	<option value="Umuahia (South East)">Umuahia (South East)</option>
	<option value="Ussa (North East)">Ussa (North East)</option>
	<option value="Uyo (South South)">Uyo (South South)</option>
	<option value="Vgc (Lekki)">Vgc (Lekki)</option>
	<option value="Warri District (Warri District)">Warri District (Warri District)</option>
	<option value="Wuse (Ajuja)">Wuse (Ajuja)</option>
	<option value="Yenagoa (South South)">Yenagoa (South South)</option>
	<option value="Yola (North East)">Yola (North East)</option>
	<option value="Zaria (North West)">Zaria (North West)</option>
	<option value="Zuru Dist (North West)">Zuru Dist (North West)</option>

</select>';

?>